-- data:extend({
--     {
--         type = "fluid",
--         name = "molten-glass",
--         icon = "__modern-nanoelectronics__/assets/icons/molten-glass.png",
--         icon_size = 64,
--         base_color = {r=0.1, g=0.1, b=0.15},
--         flow_color = {r=0.15, g=0.15, b=0.20},
--         default_temperature = 25,
--         heat_capacity = "0.1kJ",
--         barrelling_unlock_tech = "cube-tar-processing",
--   }
-- })